import { Component } from '@angular/core';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.scss']
})
export class WelcomeComponent {
  data = [
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
    'asdasd',
   ];
}
